import Link from "next/link";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";

export const metadata = {
  title: "Rodrigo Medina Porfolio",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  const pro = pages || "";
  return (
    <html lang="en" className="bg-green-50">
      <body className="max-w-6xl mx-auto py-10">
        <header className="flex items-center justify-between mx-5">
          <Link
            href="/"
            className="bg-gradient-to-r 
        from-green-400 via-violet-500 to-blue-700 
          bg-clip-text text-transparent text-lg font-bold"
          >
            Idrodrigo
          </Link>

          <div className="flex items-center gap-11 text-sm text-green-400">
            {pro.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-28 mx-10">{children}</main>
      </body>
    </html>
  );
}
